import { Component, StrictMode, useEffect, useRef, useState } from 'react';
import type { ReactNode } from 'react';
import { createRoot } from 'react-dom/client';
import * as c from './content/caseStudy';
import './styles.css';

type Mode = 'present' | 'explore';
const pad = (n:number) => String(n).padStart(2,'0');
function Tag({children}:{children:ReactNode}) {return <span className="tag">{children}</span>}
function List({items}:{items:string[]}) {return <ul className="clean-list">{items.map(x=><li key={x}>{x}</li>)}</ul>}
function Placeholder({label='Content to add'}:{label?:string}) {return <span className="placeholder">{label}</span>}
function Markdown({text}:{text:string}) {return <div className="source-detail">{text.split('\n\n').filter(x=>x.trim()&&x.trim()!=='---').map((p,i)=>p.startsWith('- ')?<List key={i} items={c.bullets(p)}/>:<p key={i}>{p.replace(/^#+ /,'').replace(/^"|"$/g,'')}</p>)}</div>}

function Modal({title,children,onClose,drawer=false}:{title:string;children:ReactNode;onClose:()=>void;drawer?:boolean}) {
  const ref=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const dialog=ref.current;const previous=document.activeElement as HTMLElement;dialog?.showModal();return()=>{dialog?.close();previous?.focus()};},[]);
  return <dialog ref={ref} className={drawer?'modal drawer':'modal'} aria-labelledby="dialog-title" onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose()}}>
    <div className="modal-content"><div className="modal-top"><Tag>{drawer?'Hypothesis register':'Experience placeholder'}</Tag><button className="icon-button" onClick={onClose} aria-label="Close dialog">×</button></div><h2 id="dialog-title">{title}</h2>{children}</div>
  </dialog>;
}
function EvidenceFields({labels}:{labels:string[]}) {return <dl className="evidence-fields">{labels.map(x=><div key={x}><dt>{x}</dt><dd><Placeholder label="Awaiting your content"/></dd></div>)}</dl>}

function Intro({open}:{open:(x:string)=>void}) {return <>
  <div className="intro-framing"><p>{c.candidateIntro.framing}</p><span>Pick a card to explore</span></div>
  <div className="flashcards">{c.candidateIntro.categories.map((name,i)=><button key={name} className={`flashcard card-${i%4}`} onClick={()=>open(name)}><span className="card-number">{pad(i+1)}</span><strong>{name}</strong><span className="card-arrow" aria-hidden="true">↗</span></button>)}</div>
  <div className="motivation"><Tag>Draft motivation</Tag><p>“{c.candidateIntro.motivation}”</p></div>
  </>}

function Scaling({explore}:{explore:boolean}) {
 const [selected,setSelected]=useState(0); const milestone=c.scalingMilestones[selected];
 const points=[[10,78],[36,63],[63,40],[89,13]];
 return <><p className="scene-subtitle">{c.scalingNarrative.subtitle}</p><div className="scaling-layout"><div className="chart-panel">
  <div className="panel-top"><Tag>Illustrative scaling journey</Tag><span>Today → FY31</span></div>
  <div className="chart" role="group" aria-label="Scaling journey: select a revenue milestone">
    <svg viewBox="0 0 600 260" preserveAspectRatio="none" role="img" aria-label="Directional revenue progression, with unmanaged complexity accelerating and managed complexity rising more slowly. Curves have no shared quantitative scale.">
      <path className="grid-line" d="M40 40H565 M40 105H565 M40 170H565 M40 235H565"/>
      <path className="complexity unmanaged" d="M60 226 C210 225 340 100 540 8"/>
      <path className="complexity managed" d="M60 231 C230 219 390 210 540 177"/>
      <path className="revenue" d="M60 203 C124 196 176 180 216 164 S325 119 378 104 S483 53 534 34"/>
    </svg>
    {points.map(([left,top],i)=><button key={i} style={{left:`${left}%`,top:`${top}%`}} className={`milestone ${selected===i?'active':''}`} aria-label={`${c.scalingMilestones[i].range}: ${c.scalingMilestones[i].title}`} aria-pressed={selected===i} onClick={()=>setSelected(i)}><span className="milestone-dot"/><span className="milestone-label">{c.scalingMilestones[i].range}</span></button>)}
  </div>
  <div className="chart-legend"><span className="purple-key">Revenue scale</span><span className="red-key">Unmanaged complexity</span><span className="green-key">Managed complexity</span></div><p className="fine-print">Conceptual curves · not a forecast or a shared numerical scale</p>
 </div><div className="milestone-detail" aria-live="polite"><div className="panel-top"><Tag>Hypothesis</Tag><span>{pad(selected+1)} / 04</span></div><p className="range">{milestone.range}</p><h2>{milestone.title}</h2><div className="detail-columns"><div><h3>Likely constraints</h3><List items={milestone.constraints}/></div><div><h3>Operating response</h3><List items={milestone.response}/></div></div>{<details open={explore||undefined}><summary>Leading signals</summary>{milestone.signals.length?<List items={milestone.signals}/>:<Placeholder label="Leading signals not supplied yet"/>}</details>}</div></div>
 <div className="mission-strip"><span aria-hidden="true">↗</span>{c.scalingNarrative.mission}</div><p className="fine-print">{c.scalingNarrative.caveat}</p></>
}

function Principles({go}:{go:(lens:number)=>void}) {return <div className="principles">{c.operatingPrinciples.map((p,i)=><article className="principle" key={p.title}><span className="large-index">{pad(i+1)}</span><div><h2>{p.title}</h2><p>{p.body}</p><button className="text-button" onClick={()=>go([1,2,3,6][i])}>Explore in the diagnostic <span aria-hidden="true">↗</span></button></div></article>)}</div>}

function Diagnosis({explore,lens,setLens}:{explore:boolean;lens:number;setLens:(n:number)=>void}) {const current=c.diagnosticLenses[lens];return <><p className="scene-subtitle">{c.diagnosticIntro}</p><div className="diagnostic-layout"><div className="lens-grid" role="group" aria-label="Diagnostic lenses">{c.diagnosticLenses.map((item,i)=><button key={item.title} className={`lens ${i===lens?'selected':''}`} onClick={()=>setLens(i)} aria-pressed={i===lens}><span>{pad(i+1)}</span>{item.title}<span aria-hidden="true">↗</span></button>)}</div><article className="lens-detail" aria-live="polite"><Tag>Diagnostic lens {pad(lens+1)}</Tag><h2>{current.title}</h2>{current.question&&<p className="lens-question">“{current.question}”</p>}<div className="topic-tags">{current.topics.map(x=><span key={x}>{x}</span>)}</div>{explore&&<details><summary>Supporting detail</summary><Markdown text={current.detail}/></details>}</article></div><div className="timeline">{c.ninetyDayPhases.map((p,i)=><div key={p.title}><span className="timeline-dot">{i+1}</span><div><small>{p.days}</small><h3>{p.title}</h3><p>{p.body}</p></div></div>)}</div><div className="day90"><span>DAY 90</span><strong>{c.day90.title}</strong></div>{explore&&<details><summary>Potential outputs</summary><List items={c.day90.outputs}/></details>}</>}

function Prioritisation({explore}:{explore:boolean}) {const [weights,setWeights]=useState(c.prioritisationCriteria.map(()=>1));return <><p className="scene-subtitle">{c.prioritisationLine}</p><div className="priority-layout"><section className="weight-panel"><div className="panel-top"><h2>Trade-off criteria</h2><button className="text-button" onClick={()=>setWeights(weights.map(()=>1))}>Reset</button></div>{c.prioritisationCriteria.map((name,i)=><label className="weight" key={name}><span>{name}</span><output>{weights[i]}</output><input type="range" min="0" max="5" step="1" value={weights[i]} onChange={e=>setWeights(weights.map((w,j)=>i===j?Number(e.target.value):w))}/></label>)}</section><section className="initiative-panel"><Tag>Illustrative initiatives · unscored</Tag><div className="initiatives">{c.illustrativeInitiatives.map((name,i)=><div key={name}><span>{pad(i+1)}</span><strong>{name}</strong><span aria-label="Not scored">—</span></div>)}</div><p className="fine-print">Listed in brief order, not ranked. Scores have not been supplied; changing weights will not produce a ranking yet.</p></section></div>{explore&&<p className="explore-note">The weighting controls are an interaction prototype. Initiative scores need your input before the ranking model can be completed.</p>}</>}

function OperatingSystem({explore}:{explore:boolean}) {return <><div className="system-flow">{c.governanceModel.map((item,i)=><article key={item.title}><span className="flow-number">{pad(i+1)}</span><h2>{item.title}</h2><p>{item.question}</p>{i<5&&<span className="flow-arrow" aria-hidden="true">→</span>}</article>)}</div><div className="learning-loop"><span aria-hidden="true">↶</span> Learning → Strategy / Priorities</div><div className="enablers"><span>Across the system</span>{c.governanceEnablers.map(x=><strong key={x}>{x}</strong>)}</div><details className="rhythm" open={explore||undefined}><summary>Minimum viable rhythm <Tag>Illustrative</Tag></summary><List items={c.minimumRhythm}/><p className="fine-print">Cadence is a mechanism, not the operating system itself.</p></details></>}

function Mobilise({explore}:{explore:boolean}) {return <><div className="federation"><section className="core"><Tag>Could eventually contain</Tag><h2>Enterprise Ops core</h2><div className="core-items">{c.deliveryModel.central.map(x=><span key={x}>{x}</span>)}</div></section><div className="federation-link" aria-hidden="true">↔</div><section className="functional"><Tag>Close to the functions</Tag><h2>Functional Ops</h2><div>{c.deliveryModel.functional.map(x=><span key={x}>{x}</span>)}</div></section></div><p className="federation-principle">{c.deliveryModel.principle}</p><div className="risks">{c.risks.map((r,i)=><article key={r.title}><span className="risk-number">0{i+1}</span><div><h3>{r.title}</h3>{explore&&<p>{r.risk}</p>}<p>{r.response}</p></div></article>)}</div><details open={explore||undefined}><summary>What I need from Nourish</summary><List items={c.deliveryModel.needs}/></details></>}

function AIStory({explore}:{explore:boolean}) {return <><div className="ai-stages">{c.aiCase.stages.map((x,i)=><span key={x}><small>{pad(i+1)}</small>{x}{i<5&&<b aria-hidden="true">→</b>}</span>)}</div><div className="ai-fields"><EvidenceFields labels={c.aiCase.fields}/></div><div className="metric-grid">{c.aiCase.metrics.map(x=><article key={x}><strong aria-label="Value not supplied">—</strong><span>{x}</span></article>)}</div><p className="fine-print">Evidence and numeric results to be supplied. No values have been assumed.</p>{explore&&<details open><summary>Supporting principles</summary><List items={c.aiCase.principles}/></details>}</>}

function Experience({open}:{open:(x:string)=>void}) {return <><p className="scene-subtitle">Select a category, then an example.</p><div className="experience-library">{c.experienceLibrary.map(group=><details key={group.title}><summary><span>{group.title}</span><small>{group.items.length} examples</small></summary><div className="experience-items">{group.items.map(x=><button key={x} onClick={()=>open(`${group.title} / ${x}`)}>{x}<span aria-hidden="true">↗</span></button>)}</div></details>)}</div><p className="fine-print">Example titles from the brief. Context, action, outcome and lesson await your content.</p></>}
function Closing({explore}:{explore:boolean}) {return <><div className="closing-path">{c.closingNarrative.steps.map((x,i)=><div key={x}><span className="closing-dot" aria-hidden="true">{i===3?'✳':pad(i+1)}</span><strong>{x}</strong>{i<4&&<b aria-hidden="true">→</b>}</div>)}</div><p className="closing-note">Operational leverage is not the end goal.</p>{explore?<blockquote className="closing-statement">{c.closingNarrative.statement}</blockquote>:<details className="closing-expand"><summary>Closing statement</summary><p>{c.closingNarrative.statement}</p></details>}<div className="closing-signoff"><span className="brand-flower" aria-hidden="true">✳</span><span>Better care.<br/><strong>Sustainable growth.</strong></span></div></>}

function readRoute(){const params=new URLSearchParams(location.search);const index=c.scenes.findIndex(s=>`#${s.id}`===location.hash);return{index:Math.max(0,index),mode:(params.get('mode')==='explore'?'explore':'present') as Mode}}
function App(){
 const [route,setRoute]=useState(readRoute);const {index,mode}=route;const explore=mode==='explore';const [lens,setLens]=useState(0);const [modal,setModal]=useState<{kind:'flash'|'experience'|'assumptions';title:string}|null>(null);const mainRef=useRef<HTMLElement>(null);const scene=c.scenes[index];
 function navigate(next:number,nextMode=mode){const bounded=Math.max(0,Math.min(9,next));setRoute({index:bounded,mode:nextMode});const url=new URL(location.href);url.hash=c.scenes[bounded].id;url.searchParams.set('mode',nextMode);history.pushState({},'',url);mainRef.current?.scrollTo({top:0});window.scrollTo({top:0});}
 useEffect(()=>{const sync=()=>setRoute(readRoute());window.addEventListener('popstate',sync);window.addEventListener('hashchange',sync);return()=>{window.removeEventListener('popstate',sync);window.removeEventListener('hashchange',sync)}},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(modal||e.altKey||e.ctrlKey||e.metaKey||e.shiftKey)return;const target=e.target as HTMLElement;if(target.closest('input,textarea,select,[contenteditable=true],dialog'))return;if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const next=Math.max(0,Math.min(9,index+(e.key==='ArrowRight'?1:-1)));setRoute({index:next,mode});const url=new URL(location.href);url.hash=c.scenes[next].id;url.searchParams.set('mode',mode);history.pushState({},'',url);mainRef.current?.scrollTo({top:0});window.scrollTo({top:0});}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[index,mode,modal]);
 const content=[<Intro open={title=>setModal({kind:'flash',title})}/>,<Scaling explore={explore}/>,<Principles go={n=>{setLens(n);navigate(3)}}/>,<Diagnosis explore={explore} lens={lens} setLens={setLens}/>,<Prioritisation explore={explore}/>,<OperatingSystem explore={explore}/>,<Mobilise explore={explore}/>,<AIStory explore={explore}/>,<Experience open={title=>setModal({kind:'experience',title})}/>,<Closing explore={explore}/>][index];
 return <div className={`app ${mode}`}><a className="skip-link" href="#scene-content" onClick={e=>{e.preventDefault();mainRef.current?.focus()}}>Skip to case study</a><aside className="sidebar"><div className="brand"><span className="brand-flower" aria-hidden="true">✳</span><div>Nourish<span>OPERATIONS FOR SCALE</span></div></div><div className="sidebar-rule"/><p className="nav-label">THE CASE STUDY</p><nav aria-label="Case-study sections">{c.scenes.map((s,i)=><a key={s.id} href={`?mode=${mode}#${s.id}`} aria-current={index===i?'step':undefined} onClick={e=>{e.preventDefault();navigate(i)}}><span>{pad(i+1)}</span>{s.name}{index===i&&<b aria-hidden="true">·</b>}</a>)}</nav><div className="sidebar-bottom"><span className="small-flower" aria-hidden="true">✳</span><p>{c.proposition}</p><small>CHRIS · CASE STUDY</small></div></aside>
 <div className="workspace"><header className="topbar"><span className="top-label">NOURISH CARE <span>/</span> OPERATIONS DIRECTOR</span><div className="mode-toggle" role="group" aria-label="Viewing mode"><button aria-pressed={!explore} onClick={()=>navigate(index,'present')}>Present</button><button aria-pressed={explore} onClick={()=>navigate(index,'explore')}>Explore</button></div></header>
 <main ref={mainRef} id="scene-content" tabIndex={-1}><section className={`scene scene-${index}`} aria-labelledby="scene-title"><div className="scene-eyebrow"><span>{pad(index+1)} <span className="eyebrow-rule"/> {scene.name}</span><span className="iteration">FIRST ITERATION</span></div><h1 id="scene-title">{scene.title}</h1><div className="scene-body">{content}</div></section></main>
 <footer className="controls"><button className="assumptions-control" onClick={()=>setModal({kind:'assumptions',title:'Strong opinions, loosely held.'})}><span aria-hidden="true">ⓘ</span> Assumptions</button><div className="progress" aria-label={`Scene ${index+1} of 10`}><span>{pad(index+1)} / 10</span><div>{c.scenes.map((s,i)=><span key={s.id} className={i<=index?'complete':''}/>)}</div></div><div className="page-controls"><span className="keyboard-hint">Use ← →</span><button className="icon-button" disabled={index===0} onClick={()=>navigate(index-1)} aria-label="Previous scene">←</button><button className="next-button" disabled={index===9} onClick={()=>navigate(index+1)}>Next <span aria-hidden="true">→</span></button></div></footer></div>
 {modal&&<Modal title={modal.title} drawer={modal.kind==='assumptions'} onClose={()=>setModal(null)}>{modal.kind==='assumptions'?<><p className="fine-print">The supplied assumption is shown below. Other evidence remains to be completed.</p>{c.assumptions.map(a=><article className="assumption" key={a.assumption}><Tag>Hypothesis · supplied in brief</Tag><h3>{a.assumption}</h3><h4>Why I currently believe it</h4><p>{a.why}</p><h4>How I would validate it</h4><p>{a.validate}</p></article>)}<div className="assumption"><h3>Scaling journey</h3><p>{c.scalingNarrative.caveat}</p><Placeholder label="Supporting evidence and validation by milestone to add"/></div><div className="claim-key"><Tag>Known / interview-derived</Tag><p>Source attribution to add where not supplied.</p><Tag>Illustrative</Tag><p>Conceptual curves and initiative examples; no forecast or priority ranking.</p></div></>:<EvidenceFields labels={modal.kind==='flash'?['One short story','One relevant outcome','What this taught me']:['Context','Action','Outcome','Lesson']}/>}</Modal>}
 </div>
}
class Boundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true}}render(){return this.state.failed?<main className="fallback"><h1>{c.proposition}</h1><p>The interactive view could not load.</p><a href="./narrative.html">Read the complete supplied brief</a></main>:this.props.children}}
createRoot(document.getElementById('root')!).render(<StrictMode><Boundary><App/></Boundary></StrictMode>);
